version: '3'
services:
  frontend:
    image: rclone-sync-hub-frontend:latest
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:5001  # 默认API地址，可通过环境变量覆盖
    networks:
      - rclone-sync-net
  backend:
    image: rclone-sync-hub-backend
    networks:
      - rclone-sync-net
    ports:
      - "5001:5001"  # 暴露后端端口

networks:
  rclone-sync-net:
    driver: bridge
