export const folder = '/folders/'
export const task = '/tasks/'
export const tree = '/folders/tree'
export const rcloneList = '/rclone/list'
export const info = '/info/'
export const originList = '/origins/list'
export const refreshOrigins = '/origins/refresh'
